apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: et-operator
  name: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: et-operator
  name: et-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: et-operator
  namespace: system
  labels:
    app: et-operator
spec:
  selector:
    matchLabels:
      app: et-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: et-operator
    spec:
      serviceAccountName: et-operator
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
