apiVersion: v1
kind: Service
metadata:
  labels:
    app: et-operator
  name: et-operator-metrics
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: et-operator
