apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: et-operator-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: et-operator-leader-election
subjects:
- kind: ServiceAccount
  name: et-operator
  namespace: default
