apiVersion: kai.alibabacloud.com/v1alpha1
kind: ScaleOut
metadata:
  name: scaleout-sample
spec:
  selector:
    name: trainingjob-sample
  script: "/usr/local/bin/scaler.sh --add"  # 包含在镜像里，内容见上文如何制作训练环境镜像
  env:
    - name: TEST1
      value: test1
    - name: TEST2
      value: test2
    - name: TEST3
      value: test3
  backoffLimit: 3    # 重试次数，暂不支持
  timeout: 60        # 回调脚本的超时间
  toAdd:
    count: 2 # required  # 需要扩容的 pod 数量