apiVersion: kai.alibabacloud.com/v1alpha1
kind: TrainingJob
metadata:
  name: trainingjob-sample
spec:
  cleanPodPolicy: Running # Running or All: 作业结束后，会删除 worker pods, 不填则所有都保留。
  etReplicaSpecs:
    launcher:
      replicas: 1 # 仅能为 1
      template:
        metadata:
          name: test
          labels:
            app: etjob
        spec:
          containers:
            - image: registry.cn-huhehaote.aliyuncs.com/lumo/horovod:master-tf2.1.0-torch1.4.0-mxnet-py3.6-gpu
              name: elastic-demo
              imagePullPolicy: Always
              command:
                - sh
                - -c
                - horovodrun -np 3 --min-np 1 --max-np 10 --host-discovery-script /usr/local/bin/discover_hosts.sh python /examples/elastic/tensorflow2_mnist_elastic.py
    worker:
      replicas: 3
      maxReplicas: 10 # 暂时无用
      minReplicas: 1  # 暂时无用
      template:
        spec:
          containers:
            - image: registry.cn-huhehaote.aliyuncs.com/lumo/horovod:master-tf2.1.0-torch1.4.0-mxnet-py3.6-gpu
              name: elastic-demo
              imagePullPolicy: Always
              resources:
                limits:
                  nvidia.com/gpu: 1  # 指定每个节点使用 GPU 数


