apiVersion: kai.alibabacloud.com/v1alpha1
kind: ScaleIn
metadata:
  name: scalein-sample
spec:
  selector:
    name: trainingjob-sample
  script: "/usr/local/bin/scaler.sh --delete"  # 包含在镜像里，内容见上文如何制作训练环境镜像
  env:
    - name: TEST1
      value: test1
    - name: TEST2
      value: test2
    - name: TEST3
      value: test3
  backoffLimit: 3  # 重试次数，暂不支持
  timeout: 60      # 回调脚本的超时间
  toDelete:
    count: 2       # 需要缩容的数量，大于等于 1；从 worker 尾缀最大的 index 依次递减开始删除; 与 podNames 互斥，如果同时填写，缩容失败、报错
#    podNames:      # 需要缩容的 pod 列表; 与 count 互斥，缩容失败、报错
#      - trainingjob-sample-worker-3
#      - trainingjob-sample-worker-4